### ISSUE TITLE
Support on system set up

### ISSUE THREAD

**Issue by chabi-fin** [OpenBioSim/sire#260]
Hello! 
I am having problems getting my full system into something SIRE can use--any tips/ideas?
Specifically, I am struggling with the solvated version of my system.
My system consists of a small molecule in openmm (espaloma parameters). If I use parmed to save the structure + topology in the amber formats PRMTOP and RST7, this works fine and I can load the system into SIRE. 

However, if I solvate the small molecule in openmm using addSolvent, the same approach does not work and the save function of the parmed structure throws a cryptic error. This is strange since I am able to simulate in openmm. 

Is there then a recommended approach for getting a solvated system into SIRE?

**Comment by lohedges** [comment]
Hi there, 

Sire has no issues reading solved systems as long as the force field parameters are in a form that it can handle.

In your case, it sounds like the issue is saving the solvated OpenMM system with ParmEd, rather than loading the result with Sire.

Have you tried using BioSimSpace to load and solvate your original system? This uses Sire data structures behind the scenes so should certainly work, unless there's something specific about the solvent model you are using. 

Cheers.

**Comment by jmichel80** [comment]
Hi @chabi-fin - the notebooks in this repo may be helpful https://github.com/michellab/EspalomaFFComparison

The discussion thread here https://github.com/michellab/EspalomaFFComparison/issues/1 should also help

**Comment by chabi-fin** [comment]
Hi @lohedges, @jmichel80 -- Excellent, your advice was very helpful! 

Using a combination of Interchange and BioSimSpace I am now able to get my solvated system into Sire, avoiding the issues with ParmEd.

Thanks!

**Comment by lohedges** [comment]
No problem, thanks for confirming.
