### ISSUE TITLE
[BUG] openmm version 8.2.0 effect SOMD due to box shape identify

### ISSUE THREAD

**Issue by Roy-Haolin-Du** [OpenBioSim/sire#265]
Hi, Lester. Hope you are well.
In recent days, I updated sire and biosimspace to the latest version. 
  biosimspace  {2024.3.0 (openbiosim/linux-64) -> 2024.4.0.dev (openbiosim/label/dev/linux-64)};  
  sire  {2024.3.1 (openbiosim/linux-64) -> 2024.4.0.dev (openbiosim/label/dev/linux-64)}
OpenMM was also updated to version **8.2.0** in the process.
When I submit somd simulation related abfe. The error occured ：

Traceback (most recent call last):
  File "/home/roy/mambaforge/envs/bsstutorials/share/Sire/scripts/somd-freenrg.py", line 224, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/roy/mambaforge/envs/bsstutorials/lib/python3.10/site-packages/sire/legacy/Tools/__init__.py", line 175, in inner
    retval = func()
  File "/home/roy/mambaforge/envs/bsstutorials/lib/python3.10/site-packages/sire/legacy/Tools/OpenMMMD.py", line 2948, in runFreeNrg
    print(f"Initial energy: {integrator.getPotentialEnergy(system)}")
RuntimeError: The box shape has changed from rectangular to triclinic.  To do this, you must call setDefaultPeriodicBoxVectors() on the System to specify a triclinic default box, then reinitialize the Context.
srun: error: batou: task 0: Exited with exit code 1

It seems like when the OpenMMMD.py getPotentialEnergy from system, the box shape can not be indentified correctly from rst7 and parm7 file. Then I downgrade the openmm version back to **8.1.2**, It works well without any error.
openmm  {8.2.0 (conda-forge/linux-64) -> 8.1.2 (conda-forge/linux-64)}

This may not be an urgent issue, but I noticed that as the versions of Sire and BSS are upgraded, the version of OpenMM will also increase. This might become a problem one day in the future. I hope this can serve as a reference to help troubleshoot issues. Thank you so much!

**Comment by lohedges** [comment]
Thanks for this. I'll debug next week. I'm surprised that we've not seen this before since OpenMM 8.2 was released about a month ago, i.e. well before the release. I've run BioSimSpace CI against the recent Sire build, but perhaps that still pulled in the older version.

**Comment by lohedges** [comment]
Sire is pinned against the minor version of OpenMM, so this constrains what is pulled in by BioSimSpace.

**Comment by Roy-Haolin-Du** [comment]
Thanks for your timely reply. 

yesterday I  'conda update -c conda-forge -c openbiosim/label/dev biosimspace sire'  to 4.0.dev. The openmm was updated to 8.2.0 automatly. The error keeps occuring. 
today, I 'mamba install openmm==8.1.2 ', this error goes away. So I report this issue kindly~

If you need any information about my configuration, free to let me know.
Thank you very much for your kind help.

**Comment by lohedges** [comment]
No problem. I'll try to reproduce on Monday and will let you know if I have any questions.

**Comment by lohedges** [comment]
Just to say that this is caused by [this] (https://github.com/openmm/openmm/issues/4548) fix in OpenMM.

**Comment by lohedges** [comment]
This is because all of the SOMD related initalise functions in the C++ set a default non-triclinic box, e.g, https://github.com/OpenBioSim/sire/blob/d1df185f83ca07ccc068dca62c84a6a5b8be5a78/corelib/src/libs/SireMove/openmmfrenergyst.cpp#L498

Later, these are then set to the actual values from the Sire system, e.g.:https://github.com/OpenBioSim/sire/blob/d1df185f83ca07ccc068dca62c84a6a5b8be5a78/corelib/src/libs/SireMove/openmmfrenergyst.cpp#L3450-L3456

I don't think the first bit is needed, so I'll see if simply removing this fixes the problem.

**Comment by lohedges** [comment]
I can confirm that I can reproduce the issue locally. The fix suggested above doesn't work, so I'll need to dig deeper. Annoyingly this means that the 2024.3.1 release is broken out of the box, so I'll need to make another patch release as soon as this is fixed. While there are tests for SOMD in BioSimSpace, non of the FEP ones use a triclinic box, hence it not being caught. (I've actually been using a local build of OpenMM so have been using 8.2 for months.) Once I've solved the issue I'll add one to the test suite.

**Comment by lohedges** [comment]
Okay, I've figured it out. The issue is in the `createContext` method. Here it correctly sets the new box vectors by calling `setDefaultPeriodicBoxVectors` on the system, but then updates the context by calling `setPeriodicBoxVectors` on the context, _then_ reinitializing. This triggers the exception: https://github.com/OpenBioSim/sire/blob/d1df185f83ca07ccc068dca62c84a6a5b8be5a78/corelib/src/libs/SireMove/openmmfrenergyst.cpp#L3458-L3486

This can be fixed be removing lines 3482 and 3483 (plus the ones for the PeriodicBox). When `context.reinitialize()` is called the box vectors are automatically propagated from the system it holds. I'll fix this for all of the SOMD C++ classes and raise a PR.

**Comment by Roy-Haolin-Du** [comment]
Thank you so much, Lester. I really appreciate you fixing this bug. 
When using OpenMM==8.1.2, the ligand couldn't be parameterized, but it works with version 8.2.0. So sometimes I needed to switch between versions for parameterization and running simulations in defferent envs. However, now, thanks to your fix, I can do in one env, help me alot. I’ll test it. 
Have a good day!

**Comment by lohedges** [comment]
No problem. Thanks again for reporting since this could have likely gone unnoticed for some time.

**Comment by lohedges** [comment]
Annoyingly it seems that the issue is platform dependent. I only see it happen for the CUDA platform, not CPU. This means that I can't add a test to validate this via the CI, since we don't have access to a GPU runner. I guess I'll just add something that I can run locally.

**Comment by Roy-Haolin-Du** [comment]
Many thanks, Lester. I have updated Openmm 8.2.0 and this bug has been fixed.

Hope you have a great 2025!

**Comment by lohedges** [comment]
No problem, thanks for confirming. Happy New Year to you too!
