### ISSUE TITLE
[BUG] StandardState.py is broken 

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/sire#80]
I have fixed an import error triggered by updates of the Sire Units code in StandardState.py
https://github.com/OpenBioSim/sire/blob/feature-fixstandardstatecorrection/wrapper/Tools/StandardState.py

This has allowed me to run the program from the command line, but I have encountered various other runtime errors. 
Running 
`standardstatecorrection -C ./somd.cfg -r traj000000001.dcd -s 1 -b 5 -d 0.25 -o 4 `
with 
[somd.zip](https://github.com/OpenBioSim/sire/files/12053158/somd.zip)
(dcd file not included in the attached) 

generates the following output

```
64], [30.611033320426944, 40.67983399118694, 40.89288466317314]]}
Traceback (most recent call last):
  File "/home/julien/miniforge3/envs/sire-dev/share/Sire/scripts/standardstatecorrection.py", line 137, in <module>
    StandardState.run(params)
  File "/home/julien/miniforge3/envs/sire-dev/lib/python3.10/site-packages/sire/legacy/Tools/__init__.py", line 175, in inner
    retval = func()
  File "/home/julien/miniforge3/envs/sire-dev/lib/python3.10/site-packages/sire/legacy/Tools/StandardState.py", line 361, in run
    weight_norm_factor = ROT / sum([x[1] for x in guest_orientations])
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'
```

The TypeError happens at a line of code introduced in this previous commit e2e370940894315838fb8f65e141baaf07050ce0 by @fjclark 

I don't understand what would have changed in Sire since November 2022 to cause this previous code to break ?

**Comment by chryswoods** [comment]
I've taken a look and don't think that this is something that has changed in sire. The `guest_orientations` object is a list of list of tuples. For example, here's the `guest_orientations` for a trial run I used with the config file you supplied;

```
GUEST = [[(( -6.414, 4.968, 1.616 ), 0.0), (( -5.984, 4.508, 0.106 ), 0.0), (( 3.606, -11.622, 1.826 ), 0.0), (( 4.616, 1.858, -1.764 ), 0.0), (( 4.176, 0.288, -1.784 ), 0.0)], [(( -4.968, -6.414, 1.616 ), 0.0), (( -4.508, -5.984, 0.106 ), 0.0), (( 11.622, 3.606, 1.826 ), 0.0), (( -1.858, 4.616, -1.764 ), 0.0),...
```

This was printed via the print line I added here

```
    guest_orientations = genOrientations(restr_dict, norientations=norient.val)
    print(f"GUEST = {guest_orientations}")
    weight_norm_factor = ROT / sum([x[1] for x in guest_orientations])
```

In this case, `x[1]` in the generator is the tuple `(( -6.414, 4.968, 1.616 ), 0.0)`. It isn't an integer, and you can't sum a tuple with an integer.

Looking into the `genOrientations` function that created this, it seems this is exactly what the data should be. The code is

```
                rotvecs = []
                #import pdb; pdb.set_trace()
                for vec in body:
                    rotvec = (rotmat*vec, weight)
                    rotvecs.append(rotvec)  
                orientations.append(rotvecs)
```

i.e. orientations is a list of lists of tuples that equal a vector (`rotate*vec`) and a weight (`weight`).

Given the code looks like it wants to sum weights, I think the line should be something like

```
weight_norm_factor = ROT / sum([x[1] for l in guest_orientations for x in l])
```

This works when I test it, but there is then another error later on;

```
Traceback (most recent call last):
  File "/Users/chris/mambaforge/envs/openbiosim/share/Sire/scripts/standardstatecorrection.py", line 137, in <module>
    StandardState.run(params)
  File "/Users/chris/mambaforge/envs/openbiosim/lib/python3.11/site-packages/sire/legacy/Tools/__init__.py", line 175, in inner
    retval = func()
             ^^^^^^
  File "/Users/chris/mambaforge/envs/openbiosim/lib/python3.11/site-packages/sire/legacy/Tools/StandardState.py", line 411, in run
    deltarot = orientation[pos][1]*weight_norm_factor # Select weight and normalise to obtain a total of ROT
               ~~~~~~~~~~~^^^^^
IndexError: list index out of range
```

This error may be just because I was debugging using fake data which may not be compatible with the config file. Could you send me the dcd file or could you test the above fix on your side?

I can't think of what changed in sire to make this not work. To be honest, I don't see how this could have worked before. The only possibility is if the line of code;

```
                for vec in body:
                    rotvec = (rotmat*vec, weight)
                    rotvecs.append(rotvec)  
                orientations.append(rotvecs)
```

should instead have been

```
                for vec in body:
                    rotvec = (rotmat*vec, weight)
                    rotvecs.append(rotvec)  
                orientations += rotvecs
```

(so this is a list of tuples, not a list of list of tuples)

**Comment by fjclark** [comment]
Thanks for looking into this.

Sorry, this is a stupid error on my part due to confusion between my own branches of sire. The code above never worked. It looks like the functioning code was never included in my original PR, but instead remained only [here](https://github.com/fjclark/Sire/blob/mdr_bugfixed_from_boresch/wrapper/Tools/StandardState.py). 

I've added back in the changes needed for this to work and am currently checking that this reproduces exactly the same answers as previously. I'll push the changes and create a PR shortly, and will update the branches linked [here](https://github.com/michellab/Multiple-Distance-Restraints).

Apologies for the wasted time.

**Comment by chryswoods** [comment]
No problem - looking into this let me find that the DCD writer was broken and motivated me to create a proper fix. Nothing is wasted, and I've made many similar mistakes myself ;-)
